# Generated by Django 5.1.4 on 2025-01-20 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Musics",
            fields=[
                (
                    "musicId",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("title", models.CharField(max_length=50)),
                ("singer", models.CharField(max_length=50)),
                ("writer", models.CharField(max_length=50)),
                (
                    "musicThumbnail",
                    models.FileField(default=None, null=True, upload_to="media/"),
                ),
                (
                    "musicFile",
                    models.FileField(default=None, null=True, upload_to="media/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "Username",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("password", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=30)),
                ("email", models.CharField(max_length=50)),
                ("mobile", models.ImageField(default=0, upload_to="")),
                ("favSinger1", models.CharField(max_length=50)),
                ("favSinger2", models.CharField(max_length=50)),
                ("favSinger3", models.CharField(max_length=50)),
            ],
        ),
    ]
