# Generated by Django 5.1.4 on 2025-01-20 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MusicPlayer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="musics",
            name="musicFile",
            field=models.FileField(
                default=None, null=True, upload_to="MusicPlayer/media/"
            ),
        ),
        migrations.AlterField(
            model_name="musics",
            name="musicThumbnail",
            field=models.FileField(
                default=None, null=True, upload_to="MusicPlayer/media/"
            ),
        ),
    ]
