# Generated by Django 5.1.4 on 2025-02-01 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MusicPlayer", "0002_alter_musics_musicfile_alter_musics_musicthumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="musics",
            name="musicFile",
            field=models.FileField(default=None, null=True, upload_to="media/"),
        ),
        migrations.AlterField(
            model_name="musics",
            name="musicThumbnail",
            field=models.FileField(default=None, null=True, upload_to="media/"),
        ),
    ]
