# Generated by Django 5.1.4 on 2025-02-03 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("MusicPlayer", "0004_remove_musics_title_musics_medium_musics_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="favSinger1",
        ),
        migrations.RemoveField(
            model_name="user",
            name="favSinger2",
        ),
        migrations.RemoveField(
            model_name="user",
            name="favSinger3",
        ),
    ]
